/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// register address
// GPIOA
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_IDR *(volatile uint32_t *)(GPIOA_BASE + 0x08)

// GPIOB
#define GPIOB_BASE 0x40010C00
#define GPIOB_CRH *(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_ODR *(volatile uint32_t *)(GPIOB_BASE + 0x0C)
#define GPIOB_CRL *(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_IDR *(volatile uint32_t *)(GPIOB_BASE + 0x08)


#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR *(volatile uint32_t *)(RCC_BASE + 0x04)

void my_wait(int x)
{
	unsigned int i , j;
	for(int i = 0; i < x ; i++)
	{
		for(int j = 0; j < 255 ; j++) ;
	}
}
void clock_init(void)
{
	// GPIOA clock enable
	RCC_APB2ENR |= (1<<2) ;
	// GPIOB clock enable
	RCC_APB2ENR |= (1<<3) ;
}

void GPIOA_init(void)
{
	GPIOA_CRL = 0x0;
	GPIOB_CRL = 0x0;

	// GPIOA1 Input Floating
	GPIOA_CRL |= 1<<6 ;

	// GPIOB1 Output push-pull
	GPIOB_CRL |= (0b01 << 4) ;

	// GPIOA13 Input Floating
	GPIOA_CRH |=  (0b01 << 22) ;
	GPIOA_CRH &= ~(0b11 << 20) ;


	// GPIOB13 Output push-pull
	GPIOB_CRH |= (0b01 << 20) ;
	GPIOB_CRH &= ~(0b11 << 22) ;

}
int main(void)
{
	clock_init();
	GPIOA_init();


	while(1)
	{
		if((GPIOA_IDR & (1<<1)) >> 1 == 0) // single press
		{
			GPIOB_ODR ^= 1 << 1;
			while(((GPIOA_IDR & (1<<1)) >> 1 == 0)) ;
		}
		if((GPIOA_IDR & (1<<13)) >> 13 == 1) // multiple press
		{
			GPIOB_ODR ^= 1 << 13;

		}
		my_wait(1);
	}

}
