/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "stm32f013x6.h"
#include "Stm32_F103C6_GPIO_Driver.h"
void my_wait(int x)
{
	volatile unsigned int i , j;
	for(int i = 0; i < x ; i++)
	{
		for(int j = 0; j < 255 ; j++) ;
	}
}
void clock_init(void)
{
	// GPIOA clock enable
	RCC_GPIOA_CLK_EN();

	// GPIOB clock enable
	RCC_GPIOB_CLK_EN();
}

//void GPIOA_init(void)
//{
//	GPIOA_CRL = 0x0;
//	GPIOB_CRL = 0x0;
//
//	// GPIOA1 Input Floating
//	GPIOA_CRL |= 1<<6 ;
//
//	// GPIOB1 Output push-pull
//	GPIOB_CRL |= (0b01 << 4) ;
//
//	// GPIOA13 Input Floating
//	GPIOA_CRH |=  (0b01 << 22) ;
//	GPIOA_CRH &= ~(0b11 << 20) ;
//
//
//	// GPIOB13 Output push-pull
//	GPIOB_CRH |= (0b01 << 20) ;
//	GPIOB_CRH &= ~(0b11 << 22) ;
//
//}
int main(void)
{
	clock_init();
	// GPIO Init
	GPIO_PinConfig PinCfg ;

	//PA1 Input HighZ
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	//PB1 Output PP Mode , Speed 10 MHz.
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_OUTPUT_SPEED_10_MHz;
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	//PA13 Input HighZ
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	//PB13 Output PP Mode , Speed 10 MHz.
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_OUTPUT_SPEED_10_MHz;
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	/* Super Loop */
	while(1)
	{
		// PA1 is connected to external PUR
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0) // single press
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0) ;
		}
		// PA13 is connected to external PDR
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1) // multiple press
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);

		}
		my_wait(1);
	}

}

