/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "stm32f013x6.h"
#include "Stm32_F103C6_GPIO_Driver.h"
#include "Stm32_F103C6_EXTI_Driver.h"
#include "LCD.h"
#include "KeyPad.h"




void my_wait(int x)
{
	volatile unsigned int i , j;
	for(int i = 0; i < x ; i++)
	{
		for(int j = 0; j < 255 ; j++) ;
	}
}
int IRQ_Flag = 0;
void EXTI9_CallBack()
{
	IRQ_Flag = 1;
	HAL_LCD_WRITE_STRING("IRQ EXTI9 Is Happen _|-");
	my_wait(10000);
}
void clock_init(void)
{
	// GPIOA clock enable
	RCC_GPIOA_CLK_EN();

	// GPIOB clock enable
	RCC_GPIOB_CLK_EN();

	// AFIO clock enable
	RCC_AFIO_CLK_EN();
}


int main(void)
{
	clock_init();
	HAL_LCD_INIT();
	HAL_LCD_CLEAR_SCREEN();
	EXTI_Config_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTI9PB9;
	EXTI_CFG.IRQ_EN = IRQ_ENABLE;
	EXTI_CFG.Trigger_Case = Trigger_Case_Rising;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_CallBack ;
	MCAL_EXTI_GPIO_Init(&EXTI_CFG);

	IRQ_Flag = 1;
	/* Super Loop */
	while(1)
	{
		if(IRQ_Flag)
		{
			HAL_LCD_CLEAR_SCREEN();
			IRQ_Flag = 0;
		}
	}

}

