/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "stm32f013x6.h"
#include "Stm32_F103C6_GPIO_Driver.h"
#include "Stm32_F103C6_EXTI_Driver.h"
#include "Stm32_F103C6_UART_Driver.h"


void clock_init(void)
{
	// GPIOA clock enable
	RCC_GPIOA_CLK_EN();

	// GPIOB clock enable
	RCC_GPIOB_CLK_EN();

	// AFIO clock enable
	RCC_AFIO_CLK_EN();
}
unsigned char data;
void Mahmoud_UART_IRQ_CallBack(void)
{
	MCAL_UART_ReceiveData(USART1, &data, disable);
	MCAL_UART_SendData(USART1, &data, enable);
}
int main(void)
{


	clock_init();

	USART_Config USART1_Config;

	USART1_Config.BaudRate = BaudRate_115200;
	USART1_Config.HwFlowCtl = HwFlowCtl_None;
	USART1_Config.IRQ_Enable = IRQ_Enable_RXNEIE;

	USART1_Config.P_IRQ_CallBack = Mahmoud_UART_IRQ_CallBack;

	USART1_Config.Parity = Parity_None;
	USART1_Config.Payload_Length = Payload_Length_8B;
	USART1_Config.StopBits = StopBits_1;
	USART1_Config.USART_Mode = USART_Mode_TX_RX;

	MCAL_UART_Init(USART1, &USART1_Config);
	MCAL_UART_GPIO_SetPins(USART1);
	/* Super Loop */
	while(1)
	{

	}

}

